name: AddPlus
version: \${project.version}
main: com.addplus.addplusplugin.AddPlusPlugin
api-version: 1.21
authors: [YourName, TraeAI]
description: \${project.description}
website: # Optional: Your project website
commands:
  addplus:
    description: Base command for AddPlus plugin.
    usage: /<command> help
    aliases: [ap]
permissions:
  addplus.use:
    description: Allows general use of AddPlus features (placeholder, actual use TBD).
    default: op
  addplus.give:
    description: Allows usage of the /addplus give command.
    default: op
  addplus.reload:
    description: Allows usage of the /addplus reload command.
    default: op
  addplus.list:
    description: Allows usage of the /addplus list command.
    default: op
  addplus.gui:
    description: Allows usage of the /addplus gui command.
    default: op
